import images from './images.js';

const tobaccos = [
    {
        type: 'Dark',
        brand: 'Element Earth',
        name: 'Peer',
        flavour: 'Pear',
        image: images.ElementEarthPeer,
        ice: false,
        fruity: true,
        sweet: true,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Element Earth',
        name: 'Cuctus Fik',
        flavour: 'Cactus fig',
        image: images.ElementEarthCuctusFik,
        ice: false,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Element Earth',
        name: 'Cherrie',
        flavour: 'Cherry',
        image: images.ElementEarthCherrie,
        ice: false,
        fruity: true,
        sweet: true,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Element Earth',
        name: 'Curant',
        flavour: 'Currant',
        image: images.ElementEarthCurant,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Element Earth',
        name: 'Fiir',
        flavour: 'Fir needles',
        image: images.ElementEarthFiir,
        ice: false,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Element Earth',
        name: 'Pinappl',
        flavour: 'Pineapple',
        image: images.ElementEarthPinappl,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Element Earth',
        name: 'Piach',
        flavour: 'Peach',
        image: images.ElementEarthPiach,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Element Earth',
        name: 'Limongras',
        flavour: 'Lemon grass',
        image: images.ElementEarthLimongras,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Element Earth',
        name: 'Irish Kriem',
        flavour: 'Irish cream, Coffee',
        image: images.ElementEarthIrishKriem,
        ice: false,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Element Earth',
        name: 'Bnana Daiqr',
        flavour: 'Banana, Lime, Alcohol',
        image: images.ElementEarthBnanaDaiqr,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Element Earth',
        name: 'Rosella Ice Crem',
        flavour: 'Vanilla ice cream with hibiscus',
        image: images.ElementEarthRosellaIceCrem,
        ice: false,
        fruity: false,
        sweet: true,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Hola',
        flavour: 'Coke',
        image: images.ElementWaterHola,
        ice: false,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Raspberrie',
        flavour: 'Raspberry',
        image: images.ElementWaterRaspberrie,
        ice: false,
        fruity: true,
        sweet: true,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Belgian Wffl',
        flavour: 'Belgian waffle with caramel',
        image: images.ElementWaterBelgianWffl,
        ice: false,
        fruity: false,
        sweet: true,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Ekzo',
        flavour: 'Watermelon, Strawberry',
        image: images.ElementWaterEkzo,
        ice: false,
        fruity: true,
        sweet: true,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Grap Mnt',
        flavour: 'Grape with mint',
        image: images.ElementWaterGrapMnt,
        ice: true,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Mng',
        flavour: 'Mango',
        image: images.ElementWaterMng,
        ice: false,
        fruity: true,
        sweet: true,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Cooki Monster',
        flavour: 'Cookies with strawberry',
        image: images.ElementWaterCookiMonster,
        ice: false,
        fruity: false,
        sweet: true,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Margarita',
        flavour: 'Margarita cockteil with lemon and lime',
        image: images.ElementWaterMargarita,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Grapefrut & Pmelo',
        flavour: 'Grapefruit, Pomelo',
        image: images.ElementWaterGrapefrutPmelo,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Wildberrie Mors',
        flavour: 'Forest fruits',
        image: images.ElementWaterWildberrieMors,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Wtrlmn Halls',
        flavour: 'Watermelon with mint',
        image: images.ElementWaterWtrlmnHalls,
        ice: true,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Choco-orng',
        flavour: 'Chocolate, Orange',
        image: images.ElementWaterChocoOrng,
        ice: false,
        fruity: true,
        sweet: true,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Element Water',
        name: 'Kiwi-strb-rasp',
        flavour: 'Kiwi, Strawberry, Raspberry',
        image: images.ElementWaterKiwiStrbRasp,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Element Air',
        name: 'Trdelnik',
        flavour: 'Nougat, Hazelnut',
        image: images.ElementAirTrdelnik,
        ice: false,
        fruity: false,
        sweet: true,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Element Air',
        name: 'Tropicana',
        flavour: 'Mango, Passionfruit, Peach',
        image: images.ElementAirTropicana,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Element Air',
        name: 'Fistacho G-lato',
        flavour: 'Pistachio ice cream',
        image: images.ElementAirFistachoGlato,
        ice: false,
        fruity: false,
        sweet: true,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Element Air',
        name: 'Berrytale',
        flavour: 'Forest berries',
        image: images.ElementAirBerrytale,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Element Air',
        name: 'Noirmlon',
        flavour: 'Melon, Blueberry',
        image: images.ElementAirNoirmlon,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Weak)',
        brand: 'Darkside Base',
        name: 'Supernova',
        flavour: 'Ice (Intense)',
        image: images.DarksideSupernova,
        ice: true,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Darkside Core',
        name: 'Supernova',
        flavour: 'Ice (Intense)',
        image: images.DarksideSupernova,
        ice: true,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Darkside Core',
        name: 'Bnpapa',
        flavour: 'Banana',
        image: images.DarksideBnpapa,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Darkside Core',
        name: 'Doppelgänger',
        flavour: 'Mastika',
        image: images.DarksideDoppelgänger,
        ice: false,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Musthave',
        name: 'Pinkman',
        flavour: 'Grapefruit, Strawberry, Raspberry syrup',
        image: images.MusthavePinkman,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Holster',
        name: 'Booster',
        flavour: 'Ice (Intense)',
        image: images.HolsterBooster,
        ice: true,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Holster',
        name: 'Bono',
        flavour: 'Wafer with milky hazelnut cream',
        image: images.HolsterBono,
        ice: false,
        fruity: false,
        sweet: true,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Holster',
        name: 'Ice Kaktuz',
        flavour: 'Cactus, Ice',
        image: images.HolsterIceKaktuz,
        ice: true,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'BlackBurn',
        name: 'Asian Lychee',
        flavour: 'Lychee',
        image: images.BlackBurnAsianLychee,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'BlackBurn',
        name: 'Irish Cream',
        flavour: 'Irish cream with a light alcoholic aftertaste, Coffee',
        image: images.BlackBurnIrishCream,
        ice: false,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'BlackBurn',
        name: 'Almond Icecream',
        flavour: 'Almond ice cream',
        image: images.BlackBurnAlmondIcecream,
        ice: false,
        fruity: false,
        sweet: true,
        inStock: true
    },
    {
        type: 'Dark (Strong)',
        brand: 'Tangiers Noir',
        name: 'Horcata',
        flavour: 'Cinnamon dessert',
        image: images.TangiersNoirHorcata,
        ice: false,
        fruity: false,
        sweet: true,
        inStock: true
    },
    {
        type: 'Dark (Strong)',
        brand: 'Tangiers Noir',
        name: 'Kashmir Piach',
        flavour: 'Spices, Peach',
        image: images.TangiersNoirKashmirPiach,
        ice: false,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Strong)',
        brand: 'Tangiers Noir',
        name: 'Marashino Cherri',
        flavour: 'Cherry with lemon and floral traces',
        image: images.TangiersNoirMarashinoCherri,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Strong)',
        brand: 'Tangiers Noir',
        name: 'Orng Zoda',
        flavour: 'Orange soda',
        image: images.TangiersNoirOrngZoda,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Strong)',
        brand: 'Tangiers Noir',
        name: 'Strwbrry',
        flavour: 'Strawberry',
        image: images.TangiersNoirStrwbrry,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Strong)',
        brand: 'Tangiers Noir',
        name: 'Ololiuqui',
        flavour: 'Coke with lime candy traces',
        image: images.TangiersNoirOloliuqui,
        ice: false,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Strong)',
        brand: 'Tangiers Noir',
        name: 'Piach Ice Tee',
        flavour: 'Peach ice tea',
        image: images.TangiersNoirPiachIceTee,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark (Extreme)',
        brand: 'Tangiers Burley',
        name: 'Absinthe',
        flavour: 'Absinthe (Alcohol)',
        image: images.TangiersBurleyAbsinthe,
        ice: false,
        fruity: false,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Zomo',
        name: 'Strong Lemon',
        flavour: 'Lemon, Ice (Strong)',
        image: images.ZomoStrongLemon,
        ice: true,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Zomo',
        name: 'Strong Orange',
        flavour: 'Orange, Ice (Strong)',
        image: images.ZomoStrongOrange,
        ice: true,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Zomo',
        name: 'Strong Melon',
        flavour: 'Melon, Ice (Strong)',
        image: images.ZomoStrongMelon,
        ice: true,
        fruity: true,
        sweet: true,
        inStock: true
    },
    {
        type: 'Dark',
        brand: 'Zomo',
        name: 'Strong Pear',
        flavour: 'Pear, Ice (Strong)',
        image: images.ZomoStrongPear,
        ice: true,
        fruity: true,
        sweet: true,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Zomo',
        name: 'My Miami Nights',
        flavour: 'Orange, Mango',
        image: images.ZomoMyMiamiNights,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Zomo',
        name: 'My Tropical Amazon',
        flavour: 'Tropical fruits',
        image: images.ZomoMyTropicalAmazon,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Zomo',
        name: 'Framboera',
        flavour: 'Raspberry, Pear',
        image: images.ZomoFramboera,
        ice: false,
        fruity: true,
        sweet: true,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Zomo',
        name: 'Laranja Peach',
        flavour: 'Orange, Peach',
        image: images.ZomoLaranjaPeach,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Zomo',
        name: 'Melorango',
        flavour: 'Melon, Strawberry',
        image: images.ZomoMelorango,
        ice: false,
        fruity: true,
        sweet: true,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Zomo',
        name: 'My Secret of Babylon',
        flavour: 'Melon, Watermelon',
        image: images.ZomoMySecretOfBabylon,
        ice: false,
        fruity: true,
        sweet: false,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Zomo',
        name: 'Tutti Frutti',
        flavour: 'Sweet gum',
        image: images.ZomoTuttiFrutti,
        ice: false,
        fruity: false,
        sweet: true,
        inStock: true
    },
    {
        type: 'Blonde',
        brand: 'Zomo',
        name: 'My Dragon Wall',
        flavour: 'Apricot, Plum, Peach, Mint',
        image: images.ZomoMyDragonWall,
        ice: true,
        fruity: true,
        sweet: false,
        inStock: true
    }
];

export default tobaccos;